# Generated by Django 3.2.17 on 2023-02-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='info',
            new_name='event_info',
        ),
    ]
