# Generated by Django 3.2.17 on 2023-02-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_accepted_usercomment_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='likes',
            new_name='attending',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='creator',
            new_name='organiser',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_image',
        ),
    ]
