# Generated by Django 3.2.17 on 2023-02-25 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20230225_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='excerpt',
            new_name='time_date',
        ),
    ]
