# Generated by Django 3.2.17 on 2023-02-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_excerpt_event_time_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
