# Generated by Django 3.2.17 on 2023-02-26 18:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_alter_event_time_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attending',
            field=models.ManyToManyField(
                blank=True,
                related_name='attending_event',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
