# Generated by Django 3.2.17 on 2023-06-10 20:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_alter_event_attending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('booking_date',
                 models.DateTimeField(
                     default=datetime.datetime.now)),
                ('event',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='blog.event')),
                ('user',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
