# Generated by Django 3.2.17 on 2023-06-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_booking_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendee',
        ),
    ]
